#!/bin/ash

# Includes
. /tmp/www/cgi-bin/constants
. /tmp/www/cgi-bin/utils

# Handlers
on_live_stop() {
    killall ffmpeg > /dev/null 2> /dev/null
    sleep 1
    rm -rf ${HDZ_LIVE_PATH}/stream* 2>&1 > /dev/null
    rm -rf ${HDZ_LIVE_PATH}/init* 2>&1 > /dev/null
    rm -rf ${HDZ_DVR_PATH}/stream* 2>&1 > /dev/null
    rm -rf ${HDZ_DVR_PATH}/init* 2>&1 > /dev/null
    echo "Status: 200 OK"
}

on_live_play() {
    killall ffmpeg > /dev/null 2> /dev/null
    sleep 1
    rm -rf ${HDZ_LIVE_PATH}/stream* 2>&1 > /dev/null
    rm -rf ${HDZ_LIVE_PATH}/init* 2>&1 > /dev/null
    rm -rf ${HDZ_DVR_PATH}/stream* 2>&1 > /dev/null
    rm -rf ${HDZ_DVR_PATH}/init* 2>&1 > /dev/null

    ffmpeg -hide_banner -loglevel fatal -i "rtsp://127.0.0.1:8554/hdzero" -c copy -start_number 0 -f hls -hls_time 2 -hls_list_size 1 -hls_flags independent_segments+delete_segments -hls_segment_type fmp4 ${HDZ_LIVE_PATH}/stream.m3u8 &

    until [ -f ${HDZ_LIVE_PATH}/stream.m3u8 ]; do
        sleep 0.1
    done

    echo "content-type: text/html":
    echo "content-length: $(wc -c <${HDZ_LIVE_M3U8})"
    echo ""

    cat ${HDZ_LIVE_M3U8}
}

# Parse Request
if [ -z $QUERY_STRING ]; then
    echo "Status: 400 Bad Request"
else
    IFS="&"
    set -- $QUERY_STRING
    key="${1%=*}"
    if [ ${key} == "play" ]; then
        on_live_play
    elif [ ${key} == "stop" ]; then
        on_live_stop
    fi
fi
