#!/bin/ash

# Includes
. /tmp/www/cgi-bin/utils

# Handlers
status_on_authenticate() {
    utils_is_client_authorized $1
}

status_on_authorize() {
    utils_is_action_authorized $1
    if [ "$?" -eq 0 ]; then
        echo "Status: 200 OK"
    else
        echo "Status: 403 Forbidden" 
    fi
}

status_on_ip() {
    echo "Content-Type: text/html"
    echo ""
    echo -n "$(ifconfig wlan0 2> /dev/null | grep inet | awk -F ' ' '{print $2}' | cut -f2 -d':')"
}

# Parse Request
if [ -z $QUERY_STRING ]; then
    echo "Status: 400 Bad Request"
else
    IFS="&"
    set -- $QUERY_STRING
    key="${1%=*}"
    if [ ${key} == "authenticate" ]; then
        status_on_authenticate "${1#*=}"
    elif [ ${key} == "authorize" ]; then
        status_on_authorize
    elif [ ${key} == "ip" ]; then
        status_on_ip
    fi
fi
